### ISSUE TITLE
CMB sims have incorrect power

### ISSUE THREAD

**Issue by msyriac** [simonsobs/mapsims#14]
First a check that the original inputs are fine (just repeating a check we've done many times with @ajvanengelen ):

```
alms = hp.read_alm("/global/cscratch1/sd/engelen/simsS1516_v0.4/data/fullskyLensedUnabberatedCMB_alm_set00_00000.fits",hdu=(1,2,3))              
TT, EE, BB, TE, EB, TB = hp.alm2cl(alms.astype(np.complex128))
```

and plot against theory:
![2019-02-15_14 04 31](https://user-images.githubusercontent.com/3674397/52878448-a483cf80-312a-11e9-886a-73336d4d584d.png)

That looks fine. Next I load one of the trial CMB sims:

```
cfile = "/global/cscratch1/sd/zonca/simonsobs/mapsims_runs/4096/cmb/0000/simonsobs_cmb_sa027_nside4096_0000.fits"
hmap = hp.read_map(cfile,field=(0,1,2))
TT = hp.anafast(hmap[0],use_weights=True)
```
and get
![2019-02-15_14 16 52](https://user-images.githubusercontent.com/3674397/52879105-62f42400-312c-11e9-9be0-fa9eb540836e.png)

The map itself looks reasonable (although I might not be able to distinguish a CMB spectrum from just a very red one like above):
![2019-02-15_14 19 12](https://user-images.githubusercontent.com/3674397/52879257-b1a1be00-312c-11e9-8cdb-41f71701b105.png)

**Comment by zonca** [comment]
Can you compare with beam?

**Comment by msyriac** [comment]
Ah of course there's a beam! :)

![2019-02-15_18 35 56](https://user-images.githubusercontent.com/3674397/52890018-98ab0400-3150-11e9-9627-108333868a11.png)

Now we're off by a weird amplitude of 2.92.

**Comment by zonca** [comment]
ok, as far as I understood, the inputs are in uK_RJ at 148GHz, so I am converting them to K_CMB.

about this, I asked your feedback here: https://github.com/simonsobs/so_pysm_models/pull/17

**Comment by msyriac** [comment]
Hmm, uK_RJ to K_CMB is just dividing by 1e6 right? However, I've plotted the above assuming the units of the map are uK_RJ (i.e theory curve is uK**2). The input alms are certainly in uK_RJ. I'll look at the conversion you made.

**Comment by zonca** [comment]
sorry, I meant uK_RJ and uK_CMB

**Comment by msyriac** [comment]
Never mind, I see the issue. The alms are in uK_CMB units, not uK_RJ.

**Comment by zonca** [comment]
ok, thanks, changed the input parameter, can you check now `/global/cscratch1/sd/zonca/simonsobs/mapsims_runs/4096/cmb/0001`

**Comment by zonca** [comment]
@msyriac can you please doublecheck the new one?

**Comment by msyriac** [comment]
Looks pretty decent after beam and pixel window correction, except maybe for high ell lensing BB. @ajvanengelen thoughts?

Ratios w.r.t. input theory
TT
![ttcomp](https://user-images.githubusercontent.com/3674397/53292346-08dc0a00-378f-11e9-922d-d80b63f3e136.png)
EE
![eecomp](https://user-images.githubusercontent.com/3674397/53292351-0e395480-378f-11e9-872d-bfa0e707e508.png)
BB
![bbcomp](https://user-images.githubusercontent.com/3674397/53292353-12fe0880-378f-11e9-8add-e3a9213b3a11.png)

**Comment by ajvanengelen** [comment]
Hi,

That is a little weird, as things seem to look better when I calculate the same thing?
https://phy-wiki.princeton.edu/polwiki/pmwiki.php?n=LensingACTnewmaps.AlexNov14

**Comment by zonca** [comment]
@msyriac @ajvanengelen are you satisfied with this comparison?
if so please close the issue.

**Comment by msyriac** [comment]
I am not fully satisfied with the agreement and would need to revisit it at a later time, so we should keep it open. I can change the issue title to something less scary.

**Comment by zonca** [comment]
I'll close it for now, please reopen if you would like to analyze it further.
