### ISSUE TITLE
Docs have incorrect API for SONoiseSimulator

### ISSUE THREAD

**Issue by msyriac** [simonsobs/mapsims#23]
Here:
https://mapsims.readthedocs.io/en/latest/models.html#noise-power-spectra-and-hitmaps

e.g. the telescope argument is no longer accepted in SONoiseSimulator initialization.

**Comment by zonca** [comment]
Thanks, once I am done with the TOD sims I'll have time to work on updating all the docs.

**Comment by zonca** [comment]
See #22 as well
