### ISSUE TITLE
Allow homogenous un-masked "scan strategy"

### ISSUE THREAD

**Issue by msyriac** [simonsobs/mapsims#40]
For testing pipeline codes, it's useful to have a mode of the SO noise simulator where no mask is applied and no hitmap variation is applied. Instead it simply populates the full sky with a homogeoneous field with the same noise power as one would obtain if SO were to observe partial sky fraction fsky, for a provided fsky.

**Comment by zonca** [comment]
wouldn't it be sufficient to have it use a sky fraction of 1 and no hitmap weighting? Then the calling pipeline could do the scaling later?

**Comment by msyriac** [comment]
That would force the end user to think about the scaling. The scaling is simple in the current noise model, but it might change in future models.

**Comment by zonca** [comment]
implemented in #44
