### ISSUE TITLE
rolloff_ell for noise sims should have a non-None value by default

### ISSUE THREAD

**Issue by msyriac** [simonsobs/mapsims#42]
We should decide on some ell below which the noise sims *by default* roll-off to zero. This might already exist in a config somewhere, but we should have the API use a default value, say 200.
(I don't think the noise maps that are produced without the roll-off are usable because of how the power blows up at large scales)

**Comment by zonca** [comment]
I ran all the simulations with `rolloff` 50, I would set that as default. See comment by @mhasself at https://github.com/simonsobs/map_based_simulations/issues/21#issuecomment-609984437

If there are no other comments on this issue, I'll set 50 as default in a few days.

**Comment by msyriac** [comment]
Setting the default to 50 sounds good to me.
