### ISSUE TITLE
CAR unit tests on travis

### ISSUE THREAD

**Issue by msyriac** [simonsobs/mapsims#48]
@zonca , feel free to disable the CAR unit tests on #44 for now. I'll keep this issue open until I've figured out a way to get the tests that depend on pixell to work on travis.

**Comment by zonca** [comment]
ok, I'll run them locally

**Comment by msyriac** [comment]
Looks like only the CAR tests are failing on #44 on Travis, and it seems it is due to an import error with pixell that I can debug later.

**Comment by msyriac** [comment]
@zonca pixell now has binaries on PyPI. I'm still in the process of making sure they can work out of the box, and I'd like to use mapsims as a guinea pig. If I were to create a PR that requires pixell to be installed in CI, what do I need to do? In this PR, I'll remove the "xfail" from the CAR tests.

**Comment by zonca** [comment]
Revert 2b25155ecccb3c08611c795d3460620531d61fab and remove xfail

**Comment by zonca** [comment]
You can also revert e740804e1a373c4f8b1af9b7cf4dfb52a7555732

**Comment by zonca** [comment]
fixed in https://github.com/simonsobs/mapsims/pull/62
