### ISSUE TITLE
Getting the noise curve for a tube

### ISSUE THREAD

**Issue by msyriac** [simonsobs/mapsims#54]
I just realized there is no actual way to get the default noise curve for a tube easily, since internally the code first does noise_curve(fsky=1), then scales it corresponding to the <Nhits> of the fsky of the hitmap. We should have a function that exposes the effective noise curve to the API without the user having to think about loading of hitmaps.

**Comment by zonca** [comment]
@msyriac see https://github.com/simonsobs/mapsims/pull/58/commits/db55c8a7aab91d651056795c208313d59967c678

**Comment by msyriac** [comment]
FYI, that PR seems to break the atmosphere=False case, since fsky is not defined in Line 738 of noise.py.

**Comment by zonca** [comment]
it would be nice to have some test cases to catch these obvious bugs, anyway, I'll fix it

**Comment by zonca** [comment]
discuss this on #58
