### ISSUE TITLE
Document in docstring what possible tubes could be

### ISSUE THREAD

**Issue by msyriac** [simonsobs/mapsims#64]
In a docstring like this:

```
Parameters
----------

tube : str
    Specify a specific tube.
```

we should provide more info on how to discover what the possible string values are. We've done this in the past, and I forget how to do it for these v2 tubes. Could we update "tube: str" docstrings to include that information?

**Comment by msyriac** [comment]
Reopening, to add one more request: what about exposing what the order of the frequency bands in a dichroic array is as well?

**Comment by msyriac** [comment]
i.e. if I get a map that has 2 components corresponding to the two arrays in the tube, which one is 90 GHz and which one is 150 GHz?

**Comment by zonca** [comment]
yes, what about an attribute named `band_id` in the Channel object?
then mention it in the docstring of methods that return dichroic maps

**Comment by msyriac** [comment]
That could work, yes!
