### ISSUE TITLE
setup.py missing

### ISSUE THREAD

**Issue by msyriac** [simonsobs/mapsims#75]
setup.py seems to be missing, so the installation instructions in the docs do not work.

**Comment by zonca** [comment]
sorry, please do `pip install .` for now

**Comment by msyriac** [comment]
This makes it difficult to develop mapsims, since one has to reinstall every time a file is changed.

**Comment by zonca** [comment]
I agree, actually if you have the requirements installed no need to install, run tests inside the folder. I'll fix the docs

**Comment by zonca** [comment]
ok, I've updated the docs.
I wanted to test `poetry` but I'm not convinced it is useful, I will leave this issue open and most probably will switch back to standard `setup.py` using the last `astropy` project template.
