### ISSUE TITLE
Global configuration file to remove hardcoded defaults

### ISSUE THREAD

**Issue by msyriac** [simonsobs/mapsims#8]
we will do a configuration option in the global configuration file, but later, for now hardcoded is fine

_Originally posted by @zonca in https://github.com/simonsobs/mapsims/pull/4_

**Comment by zonca** [comment]
yes, once we have the cmb and the noise merged we'll work on the main package that gets configuration files/options and runs the pipeline.

**Comment by zonca** [comment]
implemented in #11
